name = "JuliaConSamplePackage"
uuid = "ac247420-6a2e-4a24-a486-c6dcb0a50216"
authors = ["Sebastian Pfitzner <pfitzseb@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
ForwardDiff = "0.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
